/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project_alpabet_crud.ui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Moderncom
 */
public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    Color DefaultColor, ClickColor;

    public Mainframe() {
        initComponents();
        DefaultColor = new Color(255,255,255);
        ClickColor = new Color(200, 162, 127);
        setLogoImage("logoPos", 56, 56, lblPos);

    }

    private void setTabColor(JPanel selectedTab) {
        PosTab.setBackground(DefaultColor);
        CustomerTab.setBackground(DefaultColor);
        ProductTab.setBackground(DefaultColor);
        StockTab.setBackground(DefaultColor);
        MaterialTab.setBackground(DefaultColor);
        UserTab.setBackground(DefaultColor);

        selectedTab.setBackground(ClickColor);
    }

            
    public void setLogoImage(String imageName, int widthImage, int heightImage, JLabel label) {
        // โหลดรูปภาพ
        ImageIcon icon = new ImageIcon("./" + imageName + ".png");
        Image image = icon.getImage();

        if (image != null && image.getWidth(null) > 0) {
            // ขนาดเดิม
            int originalWidth = image.getWidth(null);
            int originalHeight = image.getHeight(null);

            // คำนวณอัตราส่วน
            float aspectRatio = (float) originalWidth / originalHeight;

            // ขนาดใหม่
            int newWidth = widthImage;
            int newHeight = heightImage;

            // คำนวณขนาดใหม่ตามอัตราส่วน โดยปรับตามความกว้างหรือความสูงก่อน
            if (widthImage / (float) heightImage > aspectRatio) {
                // ปรับตามความสูงที่กำหนด เพราะสัดส่วนที่ต้องการกว้างเกินไป
                newWidth = (int) (heightImage * aspectRatio);
            } else {
                // ปรับตามความกว้างที่กำหนด เพราะสัดส่วนที่ต้องการสูงเกินไป
                newHeight = (int) (widthImage / aspectRatio);
            }

            // ปรับขนาดรูปภาพใหม่
            Image newImage = image.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

            // ตั้งค่า ImageIcon ใหม่ที่ปรับขนาดแล้ว
            icon.setImage(newImage);
            label.setIcon(icon);
        } else {
            System.out.println("ไม่สามารถโหลดรูปภาพ: " + imageName + ".png");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        scrPanel = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        CustomerTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        ProductTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        MaterialTab = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        UserTab = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        StockTab = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        PosTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblPos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrPanel.setBackground(new java.awt.Color(255, 255, 255));
        scrPanel.setPreferredSize(new java.awt.Dimension(1055, 600));

        jPanel3.setBackground(new java.awt.Color(231, 212, 187));

        CustomerTab.setBackground(new java.awt.Color(255, 255, 255));
        CustomerTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CustomerTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustomerTab.setPreferredSize(new java.awt.Dimension(225, 50));
        CustomerTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomerTabMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Customer");

        lblCustomer.setBackground(new java.awt.Color(255, 255, 255));
        lblCustomer.setOpaque(true);

        javax.swing.GroupLayout CustomerTabLayout = new javax.swing.GroupLayout(CustomerTab);
        CustomerTab.setLayout(CustomerTabLayout);
        CustomerTabLayout.setHorizontalGroup(
            CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        CustomerTabLayout.setVerticalGroup(
            CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        ProductTab.setBackground(new java.awt.Color(255, 255, 255));
        ProductTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ProductTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProductTab.setPreferredSize(new java.awt.Dimension(97, 50));
        ProductTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProductTabMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Product");

        lblProduct.setBackground(new java.awt.Color(255, 255, 255));
        lblProduct.setOpaque(true);

        javax.swing.GroupLayout ProductTabLayout = new javax.swing.GroupLayout(ProductTab);
        ProductTab.setLayout(ProductTabLayout);
        ProductTabLayout.setHorizontalGroup(
            ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ProductTabLayout.setVerticalGroup(
            ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        MaterialTab.setBackground(new java.awt.Color(255, 255, 255));
        MaterialTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MaterialTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MaterialTab.setPreferredSize(new java.awt.Dimension(100, 50));
        MaterialTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MaterialTabMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Material");

        lblMaterial.setBackground(new java.awt.Color(255, 255, 255));
        lblMaterial.setOpaque(true);

        javax.swing.GroupLayout MaterialTabLayout = new javax.swing.GroupLayout(MaterialTab);
        MaterialTab.setLayout(MaterialTabLayout);
        MaterialTabLayout.setHorizontalGroup(
            MaterialTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaterialTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        MaterialTabLayout.setVerticalGroup(
            MaterialTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaterialTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MaterialTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        UserTab.setBackground(new java.awt.Color(255, 255, 255));
        UserTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserTab.setPreferredSize(new java.awt.Dimension(62, 50));
        UserTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserTabMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("User");

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setOpaque(true);

        javax.swing.GroupLayout UserTabLayout = new javax.swing.GroupLayout(UserTab);
        UserTab.setLayout(UserTabLayout);
        UserTabLayout.setHorizontalGroup(
            UserTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        UserTabLayout.setVerticalGroup(
            UserTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        StockTab.setBackground(new java.awt.Color(255, 255, 255));
        StockTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StockTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StockTab.setPreferredSize(new java.awt.Dimension(72, 50));
        StockTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StockTabMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Stock");

        lblStock.setBackground(new java.awt.Color(255, 255, 255));
        lblStock.setOpaque(true);

        javax.swing.GroupLayout StockTabLayout = new javax.swing.GroupLayout(StockTab);
        StockTab.setLayout(StockTabLayout);
        StockTabLayout.setHorizontalGroup(
            StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        StockTabLayout.setVerticalGroup(
            StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        PosTab.setBackground(new java.awt.Color(255, 255, 255));
        PosTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PosTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PosTab.setPreferredSize(new java.awt.Dimension(225, 50));
        PosTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PosTabMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("POS");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblPos.setBackground(new java.awt.Color(255, 255, 255));
        lblPos.setOpaque(true);

        javax.swing.GroupLayout PosTabLayout = new javax.swing.GroupLayout(PosTab);
        PosTab.setLayout(PosTabLayout);
        PosTabLayout.setHorizontalGroup(
            PosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PosTabLayout.setVerticalGroup(
            PosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(lblPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerTab, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(ProductTab, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(MaterialTab, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(StockTab, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(UserTab, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(PosTab, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(PosTab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerTab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProductTab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockTab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaterialTab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserTab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(231, 212, 187));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTabMousePressed
        setTabColor(CustomerTab);
        scrPanel.setViewportView(new CustomerPanel());
    }//GEN-LAST:event_CustomerTabMousePressed

    private void ProductTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTabMousePressed
        setTabColor(ProductTab);
        scrPanel.setViewportView(new ProductPanel());
    }//GEN-LAST:event_ProductTabMousePressed

    private void PosTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosTabMousePressed
       setTabColor(PosTab);
       scrPanel.setViewportView(new PosPanel());       
    }//GEN-LAST:event_PosTabMousePressed

    private void StockTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockTabMousePressed
       setTabColor(StockTab);
       scrPanel.setViewportView(new StockPanel());
    }//GEN-LAST:event_StockTabMousePressed

    private void MaterialTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaterialTabMousePressed
       setTabColor(MaterialTab);
       scrPanel.setViewportView(new MaterialPanel());
    }//GEN-LAST:event_MaterialTabMousePressed

    private void UserTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTabMousePressed
       setTabColor(UserTab);
       scrPanel.setViewportView(new UserPanel());
    }//GEN-LAST:event_UserTabMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerTab;
    private javax.swing.JPanel MaterialTab;
    private javax.swing.JPanel PosTab;
    private javax.swing.JPanel ProductTab;
    private javax.swing.JPanel StockTab;
    private javax.swing.JPanel UserTab;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblPos;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblUser;
    private javax.swing.JScrollPane scrPanel;
    // End of variables declaration//GEN-END:variables
}
