/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project_alpabet_crud.ui;

import com.mycompany.project_alpabet_crud.model.Material;
import com.mycompany.project_alpabet_crud.model.MaterialUserImport;
import com.mycompany.project_alpabet_crud.service.MaterialService;
import com.mycompany.project_alpabet_crud.service.MaterialUserImportService;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author teeraphat
 */
public class MaterialUserImportDialog extends javax.swing.JPanel {

    private final MaterialUserImportService mtimService;
    private final List<MaterialUserImport> listmatimp;

    /**
     * Creates new form MaterialUserImportDialog
     */
    public MaterialUserImportDialog(JFrame frame) {
        initComponents();
        mtimService = new MaterialUserImportService();
        tblEmployee.setRowHeight(100);
        listmatimp = mtimService.getMaterialUserImport();
        tblEmployee.setModel(new AbstractTableModel() {
            String[] columnName = {"ID","Date", "User Id", "User Name","Material Name","Quantity"};

            @Override
            public String getColumnName(int column) {
                return columnName[column];
            }
            
            @Override
            public int getRowCount() {
                return listmatimp.size();
            }

            @Override
            public int getColumnCount() {
                return 6;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                MaterialUserImport  materialuserimport = listmatimp.get(rowIndex);
                switch (columnIndex) {
                    case 0:
                        return materialuserimport.getId();
                    case 1:
                        return materialuserimport.getDate();
                    case 2:
                        return materialuserimport.getUserId();
                    case 3:
                        return materialuserimport.getUserName();
                    case 4:
                        return materialuserimport.getMaterialName();
                    case 5:
                        return materialuserimport.getMaterialQty();
                    default:
                        return "unknown";
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployee;
    // End of variables declaration//GEN-END:variables
}
